service: serverless-appsync-backend

frameworkVersion: '3'

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello

resources:
 Resources:
   ${file(resources.yml)}

custom:
  appSync:
    name: youtubeAppsyncApi
    authenticationType: AMAZON_COGNITO_USER_POOLS
    additionalAuthenticationProviders:
      - authenticationType: AWS_IAM
    schema: ./schema.graphql
    userPoolConfig:
      awsRegion: us-east-1
      defaultAction: ALLOW
      userPoolId: !Ref cognitoUserPool
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - type: Query
        field: getBookById
        dataSource: booksTable
      - type: Mutation
        field: createBook
        dataSource: booksTable
    dataSources:
      - type: AMAZON_DYNAMODB
        name: booksTable
        config:
          tableName: !Ref booksTable
          
